### ISSUE TITLE
How to hide min-max labels

### ISSUE THREAD

**Issue by silvrbak** [mattlaver/angular-justgage#18]
I tried hiding these labels but realized that those values are not being read. I tried updating the directive myself but I'm not fluent enough in angular yet. Any plans to add this and other options like colors?

**Comment by mattlaver** [comment]
You can hide the labels + change the colours using the options attribute. For example if you don't want to show the Min & Max labels then set showMinMax to false:

<just-gage id="test5" value="value2"
        options="{
            title: 'Dynamic, using options, with default min and max',
            levelColors: ['#CE1B21', '#D0532A', '#FFC414', '#85A137'],
            levelGradiant: false,
	    showMinMax: false
        }">
    </just-gage>

**Comment by silvrbak** [comment]
Ah, thanks
